{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  mapAccounts: |
    {{ .Values.data.mapAccounts| nindent 4 | trim }}
  mapRoles: |
    {{ .Values.data.mapRoles| nindent 4 | trim }}
  mapUsers: |
    {{ .Values.data.mapUsers| nindent 4 | trim }}
{{- end }} 